alias temp="$HOME/rpi/scripts/temp.sh"
alias shutdown="sudo shutdown now"
alias reboot="sudo reboot now"
alias baka="$HOME/rpi/scripts/baka.sh"
alias ay="vim $HOME/rpi/pi.sh"
alias speedlog="$HOME/rpi/scripts/speedlog.sh"
